#!/usr/bin/env python3
"""Localize the ratified interim faces into fonts/ and emit fonts.css.

The Quintessence ratification (24 July 2026) sets three faces:

    display / headings   PP Editorial New 400   interim: Sentient      (Fontshare)
    body / UI / labels   PP Neue Montreal       interim: General Sans  (Fontshare)
    mono / datum         IBM Plex Mono          final                  (Google)

A commissioning document has to render identically on any machine and years
from now, so nothing is fetched at render time. This script pulls the woff2
payloads once, writes them beside the document, and rewrites the CSS to point
at the local copies.

Two upstreams, two shapes:

  Fontshare serves one variable @font-face per style (roman, italic) across a
  200-700 weight range, with no unicode-range subsetting. Only the woff2 src
  is kept; the woff and truetype fallbacks are dropped, since Chrome renders
  the PDF and Chrome has had woff2 for a decade.

  Google serves one @font-face per unicode subset, distinguished by nothing
  but the unicode-range descriptor. Those descriptors are preserved verbatim
  -- drop them and the browser cannot tell the subsets apart.

Run this once per checkout, or whenever a licensed PP file supersedes an
interim face. Re-running is safe and overwrites in place.
"""

from __future__ import annotations

import pathlib
import re
import urllib.request

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

FONTSHARE_URL = (
    "https://api.fontshare.com/v2/css"
    "?f[]=sentient@1,2&f[]=general-sans@1,2&display=swap"
)
GOOGLE_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=IBM+Plex+Mono:wght@400;500&display=swap"
)

ROOT = pathlib.Path(__file__).parent
FONT_DIR = ROOT / "fonts"

HEADER = """/* Five Points Digital Studio -- Commissioning Proposal A4
   Local font subsets. Generated by localize_fonts.py; do not hand-edit.

   Sentient stands in for PP Editorial New, General Sans for PP Neue Montreal.
   When the licensed PP files land, drop them in fonts/ and declare them under
   their real family names -- the font stacks in proposal.html already name PP
   first, so the document upgrades itself with no rule changes.
*/
"""


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request) as response:
        return response.read()


def slug(family: str, style: str, weight: str) -> str:
    weight = weight.replace(" ", "_")
    return f"{family.replace(' ', '')}-{weight}-{style}"


def save(url: str, filename: str) -> None:
    if url.startswith("//"):
        url = f"https:{url}"
    (FONT_DIR / filename).write_bytes(fetch(url))


def fontshare_blocks() -> list[str]:
    """One variable @font-face per style. woff2 only, local path."""
    css = fetch(FONTSHARE_URL).decode()
    blocks = []
    for block in re.findall(r"@font-face\s*\{[^}]+\}", css):
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*([^;]+);", block).group(1).strip()
        style = re.search(r"font-style:\s*([^;]+);", block).group(1).strip()
        url = re.search(r"url\('(//[^']+\.woff2)'\)", block).group(1)

        filename = f"{slug(family, style, weight)}.woff2"
        save(url, filename)

        # Collapse the three-format src down to the local woff2.
        block = re.sub(
            r"src:.*?;",
            f"src: url(fonts/{filename}) format('woff2');",
            block,
            flags=re.DOTALL,
        )
        blocks.append(block)
        print(f"  {filename}  [{style} {weight}]")
    return blocks


def google_blocks() -> list[str]:
    """One @font-face per unicode subset. unicode-range must survive."""
    css = fetch(GOOGLE_URL).decode()
    blocks = []
    counter: dict[str, int] = {}
    for block in re.findall(r"/\*[^*]+\*/\s*@font-face\s*\{[^}]+\}", css):
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*([^;]+);", block).group(1).strip()
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        urange = re.search(r"unicode-range:\s*([^;]+);", block).group(1).strip()

        key = slug(family, "normal", weight)
        counter[key] = counter.get(key, 0) + 1
        filename = f"{key}-{counter[key]}.woff2"
        save(url, filename)

        blocks.append(block.replace(url, f"fonts/{filename}"))
        print(f"  {filename}  [{urange[:44]}...]")
    return blocks


def main() -> None:
    FONT_DIR.mkdir(exist_ok=True)

    print("Fontshare -- Sentient, General Sans")
    blocks = fontshare_blocks()

    print("\nGoogle -- IBM Plex Mono")
    blocks += google_blocks()

    (ROOT / "fonts.css").write_text(HEADER + "\n" + "\n".join(blocks) + "\n")
    print(f"\nWrote fonts.css with {len(blocks)} @font-face blocks")


if __name__ == "__main__":
    main()
