#!/usr/bin/env python3
"""Localize the ratified interim faces into fonts/ and emit fonts.css.

The Quintessence ratification (24 July 2026) sets three faces:

    display / headings   PP Editorial New 400   interim: Sentient      (Fontshare)
    body / UI / labels   PP Neue Montreal       interim: General Sans  (Fontshare)
    mono / datum         IBM Plex Mono          final                  (Google)

A commissioning document has to render identically on any machine and years
from now, so nothing is fetched at render time. This script pulls the font
payloads once, writes them beside the document, and generates the CSS that
serves them.

Two upstreams, two shapes:

  Fontshare serves one variable woff2 per style (roman, italic) across a
  200-700 weight range. Those files are downloaded but never served: they
  are the sources that static instances are cut from (see below).

  Google serves one @font-face per unicode subset, distinguished by nothing
  but the unicode-range descriptor. Those descriptors are preserved verbatim
  -- drop them and the browser cannot tell the subsets apart. IBM Plex Mono
  is already static, so its files are served as they arrive.

THE VARIABLE FONT RULE. A variable font must never reach Chrome's print
pipeline. page.pdf() embeds variable fonts as Type 3 glyph procedures with
bad bounding boxes, and strict PDF viewers -- pdf.js above all -- draw the
words overlapping and stacked. Chrome, poppler and CoreGraphics all render
the same file fine, which is how the defect shipped undetected. So after
downloading, this script cuts static instances from the variable files with
fontTools at exactly the weights the stylesheet requests (the INSTANCES
table below), and fonts.css serves only those statics, as TTF, which Chrome
embeds as healthy CID TrueType.

The corollary: every weight the document can request, including by
inheritance, must exist as a real face. When a requested weight is missing
Chrome synthesizes it from the nearest face, and synthetic bold embeds as
Type 3 through the same path. That is why IBM Plex Mono is pulled at 600
as well as 400 and 500. Diagnosis on any built PDF:

    pdffonts proposal.pdf    # any "Type 3" row is the defect

fontTools is required, so run through an ephemeral environment, matching
build.py:

    uv run --with "fonttools[woff]" python localize_fonts.py

Run once per checkout, or whenever a licensed PP file supersedes an interim
face. Re-running is safe and overwrites in place. If a stylesheet rule
starts requesting a weight or style not listed in INSTANCES, add the row
and re-run.
"""

from __future__ import annotations

import pathlib
import re
import sys
import urllib.request

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

# One request per family: the API's multi-family form (?f[]=a&f[]=b) began
# returning only the first family, observed August 2026.
FONTSHARE_FAMILIES = ["sentient@1,2", "general-sans@1,2"]
FONTSHARE_URL = "https://api.fontshare.com/v2/css?f[]={family}&display=swap"
# 600 is served as a real face because guillemet slots inherit font-weight
# from semibold parents (the cover strong, the finding h3). Without it Chrome
# synthesizes bold from Medium and embeds the synthetic glyphs as Type 3 --
# the same defect class as the variable fonts, via a second mechanism.
GOOGLE_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=IBM+Plex+Mono:wght@400;500;600&display=swap"
)

ROOT = pathlib.Path(__file__).parent
FONT_DIR = ROOT / "fonts"

# Static instances to cut from the variable downloads: (family, style, weight).
# Exactly the weights the proposal stylesheet requests from the two Fontshare
# families -- Sentient carries the serif voice at 400 roman and italic, General
# Sans carries body at 400 and labels/headings at 600. Every font-weight: 500
# in the stylesheet is IBM Plex Mono, which needs no row here.
INSTANCES = [
    ("Sentient", "normal", 400),
    ("Sentient", "italic", 400),
    ("General Sans", "normal", 400),
    ("General Sans", "normal", 600),
]

HEADER = """/* Five Points Digital Studio -- Commissioning Proposal A4
   Local font subsets. Generated by localize_fonts.py; do not hand-edit.

   Sentient stands in for PP Editorial New, General Sans for PP Neue Montreal.
   When the licensed PP files land, drop them in fonts/ and declare them under
   their real family names -- the font stacks in proposal.html already name PP
   first, so the document upgrades itself with no rule changes.
*/
"""

STATIC_NOTE = """/* Static instances cut from the variable downloads (fontTools instancer).
   Chrome's print pipeline embeds variable fonts as Type 3 glyph procedures,
   which stack glyphs in strict PDF viewers; static instances embed as CID
   TrueType and render everywhere. The *-200_700-* variable files stay in
   fonts/ as cutting sources only -- never serve them. */"""

STATIC_BLOCK = """@font-face {{
  font-family: '{family}';
  src: url(fonts/{filename}) format('truetype');
  font-weight: {weight};
  font-display: swap;
  font-style: {style};
}}"""


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request) as response:
        return response.read()


def slug(family: str, style: str, weight: str) -> str:
    weight = weight.replace(" ", "_")
    return f"{family.replace(' ', '')}-{weight}-{style}"


def save(url: str, filename: str) -> None:
    if url.startswith("//"):
        url = f"https:{url}"
    (FONT_DIR / filename).write_bytes(fetch(url))


def fontshare_sources() -> dict[tuple[str, str], pathlib.Path]:
    """Download one variable woff2 per family/style. Cutting sources only."""
    sources: dict[tuple[str, str], pathlib.Path] = {}
    for spec in FONTSHARE_FAMILIES:
        css = fetch(FONTSHARE_URL.format(family=spec)).decode()
        for block in re.findall(r"@font-face\s*\{[^}]+\}", css):
            family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
            weight = re.search(r"font-weight:\s*([^;]+);", block).group(1).strip()
            style = re.search(r"font-style:\s*([^;]+);", block).group(1).strip()
            url = re.search(r"url\('(//[^']+\.woff2)'\)", block).group(1)

            filename = f"{slug(family, style, weight)}.woff2"
            save(url, filename)
            sources[(family, style)] = FONT_DIR / filename
            print(f"  {filename}  [{style} {weight}]")

    missing = {(f, s) for f, s, _ in INSTANCES} - sources.keys()
    if missing:
        sys.exit(f"Fontshare response is missing needed faces: {sorted(missing)}")
    return sources


def cut_static_instances(
    sources: dict[tuple[str, str], pathlib.Path],
) -> list[str]:
    """Pin each INSTANCES row to a static TTF and emit its @font-face block."""
    from fontTools.ttLib import TTFont
    from fontTools.varLib import instancer

    blocks = [STATIC_NOTE]
    for family, style, weight in INSTANCES:
        source = sources[(family, style)]
        filename = f"{slug(family, style, str(weight))}.ttf"

        font = TTFont(source)
        # Pin every axis, not just wght, so the output is fully static even
        # if the upstream file grows new axes.
        axes = {axis.axisTag: axis.defaultValue for axis in font["fvar"].axes}
        axes["wght"] = weight
        instancer.instantiateVariableFont(font, axes, inplace=True)
        font.flavor = None  # plain TTF; Chrome embeds it as CID TrueType
        font.save(FONT_DIR / filename)

        blocks.append(
            STATIC_BLOCK.format(
                family=family, filename=filename, weight=weight, style=style
            )
        )
        print(f"  {filename}  [{style} {weight} <- {source.name}]")
    return blocks


def google_blocks() -> list[str]:
    """One @font-face per unicode subset. unicode-range must survive."""
    css = fetch(GOOGLE_URL).decode()
    blocks = []
    counter: dict[str, int] = {}
    for block in re.findall(r"/\*[^*]+\*/\s*@font-face\s*\{[^}]+\}", css):
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*([^;]+);", block).group(1).strip()
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        urange = re.search(r"unicode-range:\s*([^;]+);", block).group(1).strip()

        key = slug(family, "normal", weight)
        counter[key] = counter.get(key, 0) + 1
        filename = f"{key}-{counter[key]}.woff2"
        save(url, filename)

        blocks.append(block.replace(url, f"fonts/{filename}"))
        print(f"  {filename}  [{urange[:44]}...]")
    return blocks


def main() -> None:
    try:
        import fontTools  # noqa: F401
    except ImportError:
        sys.exit(
            "fontTools is missing, so the static-instance cut cannot run.\n"
            'Invoke as:  uv run --with "fonttools[woff]" python localize_fonts.py'
        )

    FONT_DIR.mkdir(exist_ok=True)

    print("Fontshare -- Sentient, General Sans (variable cutting sources)")
    sources = fontshare_sources()

    print("\nStatic instances -- the faces fonts.css serves")
    blocks = cut_static_instances(sources)

    print("\nGoogle -- IBM Plex Mono")
    blocks += google_blocks()

    css = HEADER + "\n" + "\n".join(blocks) + "\n"
    (ROOT / "fonts.css").write_text(css)
    print(f"\nWrote fonts.css with {css.count('@font-face')} @font-face blocks")


if __name__ == "__main__":
    main()
