"""Maps the legacy 698-term Pull-for vocabulary onto the controlled taxonomy
ratified 2026-09-14. Each legacy term resolves to zero or more Pull-for handles,
zero or more Themes, or falls through to Domains as a subject descriptor."""

PULL_FOR = {
    "Posture": ["restraint", "maximalism", "high-low", "subversion", "reinvention", "conviction", "anti-logo"],
    "Voice and story": ["voice-and-tone", "narrative", "world-building", "editorial", "cadence", "long-form-structure"],
    "Visual and space": ["art-direction", "spatial-direction", "materiality", "color-and-light", "typography", "scale"],
    "Atmosphere": ["immersive-atmosphere", "warmth", "texture"],
    "Sound": ["sound-design"],
    "Craft": ["craft", "fabric-first", "precision", "provenance", "structural-honesty"],
    "Strategy and offer": ["positioning", "offer-design", "merchandising", "hospitality", "ritual",
                           "institution-building", "ownership-as-strategy", "curation-strategy", "taste-authority"],
    "Argument and rhetoric": ["rhetoric", "moral-clarity", "essay-as-form", "self-authorship",
                              "proof-as-argument", "evidence", "self-education"],
    "Nature and place": ["biophilic", "nature-integration", "indoor-outdoor", "sense-of-place", "wellbeing"],
    "Heritage": ["heritage", "diaspora", "cultural-bridge"],
    "Register": ["quiet-luxury", "investment-luxury", "accessible-luxury"],
}

THEMES = ["coming-of-age", "cost-of-greatness", "ambition-and-hubris", "moral-decay", "class-and-identity",
          "cultural-identity", "belonging-and-exclusion", "found-family", "mentor-dynamics", "legacy",
          "transformation", "perseverance", "vulnerability", "emotional-honesty", "nostalgia", "fatalism",
          "dreams-and-ambition", "self-invention"]

# legacy term -> (pull handles, themes). Absent terms fall through to Domains.
MAP = {
"Black-Atlantic-tradition": (["heritage", "diaspora"], []),
"Black-joy": ([], ["cultural-identity"]),
"British-comedic-lens": (["voice-and-tone"], []),
"Houston-mythology": (["sense-of-place", "world-building"], []),
"New-York-as-world": (["world-building", "sense-of-place"], []),
"abstract": (["art-direction"], []),
"accessible": (["accessible-luxury"], []),
"accessible luxury": (["accessible-luxury"], []),
"accessible-cool": (["accessible-luxury"], []),
"accessible-luxury": (["accessible-luxury"], []),
"accessible-modern": (["accessible-luxury"], []),
"against-the-system": (["subversion"], []),
"almanac": (["proof-as-argument"], []),
"ambition-and-hubris": ([], ["ambition-and-hubris"]),
"ambition-as-form": ([], ["ambition-and-hubris"]),
"ancestral-reference": (["heritage"], []),
"ancestral-tribute": (["heritage"], []),
"anti-colonial": (["subversion"], []),
"anti-establishment": (["subversion"], []),
"anti-formula direction": (["subversion"], []),
"anti-logo": (["anti-logo"], []),
"anti-luxury-luxury": (["anti-logo"], []),
"anti-pretty": (["subversion"], []),
"anti-silo": (["curation-strategy"], []),
"anti-style": (["subversion"], []),
"anti-style direction": (["subversion"], []),
"anti-trend": (["subversion"], []),
"architecture-as-destination": (["spatial-direction"], []),
"art-and-science": (["craft"], []),
"art-direction": (["art-direction"], []),
"art-fashion": (["high-low"], []),
"artisan": (["craft"], []),
"artisan-collaboration": (["craft"], []),
"artist-development": (["institution-building"], []),
"artistic-direction": (["art-direction"], []),
"atmosphere": (["immersive-atmosphere"], []),
"auteur": (["art-direction"], []),
"autobiography-as-cuisine": (["self-authorship"], []),
"avant-garde": (["subversion"], []),
"bean-to-bar": (["provenance"], []),
"beauty-as-function": (["structural-honesty"], []),
"belonging-and-exclusion": ([], ["belonging-and-exclusion"]),
"biophilic": (["biophilic"], []),
"blending": (["craft"], []),
"brand-architecture": (["institution-building"], []),
"brand-building": (["institution-building"], []),
"brand-identity": (["positioning"], []),
"brand-storytelling": (["narrative"], []),
"breadth": (["curation-strategy"], []),
"cadence": (["cadence"], []),
"canon-setting": (["taste-authority"], []),
"catalog-longevity": (["positioning"], []),
"category-leadership": (["positioning"], []),
"certified-sourcing": (["provenance"], []),
"chaos-and-meaning": ([], ["emotional-honesty"]),
"character-flaw": ([], ["vulnerability"]),
"character-study": ([], ["emotional-honesty"]),
"character-styling": (["art-direction"], []),
"chocolate-as-gastronomy": (["craft"], []),
"cinematography": (["art-direction"], []),
"clarity": (["structural-honesty"], []),
"class-and-identity": ([], ["class-and-identity"]),
"clean-line": (["restraint"], []),
"climate-responsive": (["nature-integration"], []),
"code-switching": ([], ["cultural-identity"]),
"cohesion": (["restraint"], []),
"collaborative-range": (["craft"], []),
"collectible": (["investment-luxury"], []),
"collective-and-sovereign": (["ownership-as-strategy"], []),
"color-and-light": (["color-and-light"], []),
"colour-confidence direction": (["color-and-light"], []),
"coming-of-age": ([], ["coming-of-age"]),
"commodity-as-icon": (["high-low"], []),
"community-dynamics": ([], ["belonging-and-exclusion"]),
"concealed-technology": (["restraint"], []),
"concealment": (["restraint"], []),
"concept-led": (["art-direction"], []),
"connoisseurship": (["taste-authority"], []),
"consequence": ([], ["moral-decay"]),
"conservation-as-purpose": (["nature-integration"], []),
"constrained-maximalism framing": (["maximalism", "restraint"], []),
"constraint-as-depth": (["restraint"], []),
"constraint-as-engine": (["restraint"], []),
"context-as-content": (["subversion"], []),
"conversion": (["offer-design"], []),
"conviction": (["conviction"], []),
"convivial": (["hospitality"], []),
"cost-of-greatness": ([], ["cost-of-greatness"]),
"cost-of-the-climb": ([], ["cost-of-greatness"]),
"couture": (["investment-luxury"], []),
"craft": (["craft"], []),
"craft-aesthetics": (["craft"], []),
"craft-led": (["craft"], []),
"craft-led direction": (["craft"], []),
"craft-over-brand": (["craft", "anti-logo"], []),
"craftsman": (["craft"], []),
"craftsmanship": (["craft"], []),
"creative-risk": (["conviction"], []),
"creative-risk direction": (["conviction"], []),
"creative-risk framing": (["conviction"], []),
"cross-category alignment": (["positioning"], []),
"cross-disciplinary direction": (["reinvention"], []),
"crossover-ambition": ([], ["ambition-and-hubris"]),
"cult-object": (["positioning"], []),
"cultural affiliation": ([], ["cultural-identity"]),
"cultural-bridge": (["cultural-bridge"], []),
"cultural-credibility": (["cultural-bridge"], []),
"cultural-custodian": (["heritage"], []),
"cultural-identity": ([], ["cultural-identity"]),
"cultural-reach": (["positioning"], []),
"cultural-reference": (["high-low"], []),
"culture-making": (["institution-building"], []),
"curated-decor": (["curation-strategy"], []),
"curated-palette": (["curation-strategy"], []),
"curation strategy": (["curation-strategy"], []),
"curation-strategy": (["curation-strategy"], []),
"debut-grammar": (["art-direction"], []),
"decision-design": (["offer-design"], []),
"defiance": (["subversion"], []),
"density-over-simplification": (["structural-honesty"], []),
"depth-of-attention": (["restraint"], []),
"design-conscious": (["art-direction"], []),
"design-conscious products": (["art-direction"], []),
"design-democratization": (["accessible-luxury"], []),
"designer-collaboration": (["curation-strategy"], []),
"desire-and-identity": ([], ["emotional-honesty"]),
"detail": (["precision"], []),
"dialogue-as-set-piece": (["voice-and-tone"], []),
"dialogue-as-suspense": (["voice-and-tone"], []),
"diaspora": (["diaspora"], []),
"direct-trade": (["provenance"], []),
"discipline": (["precision"], []),
"discreet-luxury": (["quiet-luxury"], []),
"displacement": ([], ["belonging-and-exclusion"]),
"distressed": (["texture"], []),
"distribution": (["ownership-as-strategy"], []),
"dramatic structure": (["long-form-structure"], []),
"dramatic-catharsis": (["long-form-structure"], []),
"dramatic-inevitability": (["long-form-structure"], []),
"dramatic-structure": (["long-form-structure"], []),
"dream-logic": (["immersive-atmosphere"], []),
"dreams-and-ambition": ([], ["dreams-and-ambition"]),
"ear-candy": (["sound-design"], []),
"ear-candy framing": (["sound-design"], []),
"earthy-palette": (["color-and-light"], []),
"ecological-function": (["nature-integration"], []),
"editorial": (["editorial"], []),
"editorial filter": (["curation-strategy"], []),
"editorial-risk": (["editorial"], []),
"effortless": (["restraint"], []),
"effortless-nonchalance": (["restraint"], []),
"elegant": (["restraint"], []),
"elevated-basics": (["accessible-luxury"], []),
"elevated-design": (["art-direction"], []),
"embodiment": (["immersive-atmosphere"], []),
"emotional-honesty": ([], ["emotional-honesty"]),
"emotional-range": ([], ["emotional-honesty"]),
"emotional-restraint": (["restraint"], []),
"emotional-suppression": ([], ["vulnerability"]),
"emotional-weight": ([], ["emotional-honesty"]),
"empire-pivot": (["ownership-as-strategy"], []),
"energy-flow": (["spatial-direction"], []),
"engagement-loop": (["offer-design"], []),
"engineering-of-delight": (["structural-honesty"], []),
"engineering-of-ease": (["structural-honesty"], []),
"ensemble-structure": (["long-form-structure"], []),
"equity": (["provenance"], []),
"era-pacing": (["positioning"], []),
"essay-as-form": (["essay-as-form"], []),
"ethics": (["provenance"], []),
"ethics-as-operations": (["provenance"], []),
"everyday-chic": (["accessible-luxury"], []),
"evidence": (["evidence"], []),
"evidence-based-nutrition": (["evidence"], []),
"excellence": (["precision"], []),
"excellence direction": (["precision"], []),
"experience design": (["hospitality"], []),
"experiential": (["hospitality"], []),
"exposed-structure": (["structural-honesty"], []),
"fabric-architecture": (["materiality"], []),
"fabric-first": (["fabric-first"], []),
"family-craft": (["craft"], []),
"fashion-as-culture": (["cultural-bridge"], []),
"fatal-flaw-structure": (["long-form-structure"], []),
"fatalism": ([], ["fatalism"]),
"film-direction": (["art-direction"], []),
"five-star hospitality": (["hospitality"], []),
"five-year-plan": (["institution-building"], []),
"flavor-invention": (["craft"], []),
"flavor-pairing": (["craft"], []),
"focus": (["restraint"], []),
"food-culture direction": (["cultural-bridge"], []),
"food-science": (["evidence"], []),
"form-follows-function": (["structural-honesty"], []),
"form-invention": (["reinvention"], []),
"formal-experimentation": (["reinvention"], []),
"formulation": (["craft"], []),
"forward-looking-heritage": (["heritage"], []),
"found-family": ([], ["found-family"]),
"found-materials": (["materiality"], []),
"french-luxury": (["investment-luxury"], []),
"french-technique": (["craft"], []),
"freshness-first": (["provenance"], []),
"friendship-as-structure": ([], ["found-family"]),
"furniture-as-topography": (["spatial-direction"], []),
"fusion": (["cultural-bridge"], []),
"garden-room": (["indoor-outdoor"], []),
"genre-blur": (["reinvention"], []),
"genre-inversion": (["subversion"], []),
"glass": (["materiality"], []),
"glass-room": (["indoor-outdoor"], []),
"green-saturation": (["biophilic"], []),
"greenery": (["biophilic"], []),
"habitat-gardening": (["nature-integration"], []),
"haute-chocolate": (["craft"], []),
"haute-parfumerie": (["craft"], []),
"health-as-foundation": (["wellbeing"], []),
"heritage": (["heritage"], []),
"heritage craft": (["heritage", "craft"], []),
"heritage-coded": (["heritage"], []),
"heritage-forward": (["heritage"], []),
"heritage-preservation": (["heritage"], []),
"heroic-posture": (["art-direction"], []),
"high-low": (["high-low"], []),
"high-street": (["accessible-luxury"], []),
"historical-fabric": (["heritage"], []),
"historical-weight": ([], ["legacy"]),
"history": ([], ["legacy"]),
"hit-factory": (["institution-building"], []),
"horizontal-calm": (["spatial-direction"], []),
"horizontal-massing": (["spatial-direction"], []),
"hospitality": (["hospitality"], []),
"humor-as-armor": ([], ["vulnerability"]),
"icon-making": (["positioning"], []),
"identity": ([], ["cultural-identity"]),
"identity-formation": ([], ["self-invention"]),
"image-as-argument": (["self-authorship", "art-direction"], []),
"image-first": (["art-direction"], []),
"immersive-atmosphere": (["immersive-atmosphere"], []),
"imperfection-as-design": (["texture"], []),
"improvisation": (["craft"], []),
"indoor-outdoor": (["indoor-outdoor"], []),
"information-design": (["structural-honesty", "evidence"], []),
"inhabitable-sculpture": (["scale"], []),
"innocence-as-wisdom": ([], ["emotional-honesty"]),
"institution-building": (["institution-building"], []),
"institutional-authority": (["taste-authority"], []),
"institutional-warmth": (["warmth"], []),
"integration": (["restraint"], []),
"intelligent-comfort": (["structural-honesty"], []),
"intention-density": (["maximalism"], []),
"interior integration": (["spatial-direction"], []),
"investment-luxury": (["investment-luxury"], []),
"joinery": (["craft"], []),
"juxtaposition": (["high-low"], []),
"kinetic": (["art-direction"], []),
"kinetic-camera": (["art-direction"], []),
"land-as-system": (["nature-integration"], []),
"landscape-integration": (["nature-integration"], []),
"layered-composition": (["color-and-light"], []),
"layered-reality": (["immersive-atmosphere"], []),
"legacy": ([], ["legacy"]),
"lexicon-as-brand": (["voice-and-tone"], []),
"light": (["color-and-light"], []),
"light-as-material": (["color-and-light"], []),
"light-capture": (["color-and-light"], []),
"lineage": (["heritage"], []),
"logo-avoidance": (["anti-logo"], []),
"long-form-structure": (["long-form-structure"], []),
"longevity": (["wellbeing"], []),
"luxury": (["investment-luxury"], []),
"maison": (["heritage"], []),
"maker-craft": (["craft"], []),
"market-hall": (["merchandising"], []),
"mastery": (["precision"], []),
"materiality": (["materiality"], []),
"maximalism": (["maximalism"], []),
"maximalist": (["maximalism"], []),
"memorial": ([], ["legacy"]),
"memory-and-mood": ([], ["nostalgia"]),
"menswear curation": (["curation-strategy"], []),
"mentor dynamics": ([], ["mentor-dynamics"]),
"mentor-dynamics": ([], ["mentor-dynamics"]),
"merchandising": (["merchandising"], []),
"minimal-intervention": (["restraint"], []),
"minimalism": (["restraint"], []),
"modular": (["structural-honesty"], []),
"monumental": (["scale"], []),
"moody-dining": (["immersive-atmosphere"], []),
"moody-intimacy": (["immersive-atmosphere"], []),
"moral-clarity": (["moral-clarity"], []),
"moral-decay": ([], ["moral-decay"]),
"moral-transformation": ([], ["transformation"]),
"moral-weight": (["moral-clarity"], []),
"multi-generational": ([], ["legacy"]),
"multiple-perspective": (["reinvention"], []),
"music-and-rhythm": (["sound-design"], []),
"music-as-structure": (["sound-design"], []),
"naming": (["positioning"], []),
"narrative": (["narrative"], []),
"narrative-structure": (["narrative", "long-form-structure"], []),
"native-species": (["nature-integration"], []),
"natural-fibre": (["materiality"], []),
"natural-materials": (["materiality"], []),
"naturalism": (["restraint"], []),
"nature": (["nature-integration"], []),
"nature-forward": (["nature-integration"], []),
"nature-immersion": (["nature-integration"], []),
"nature-inside": (["biophilic"], []),
"nature-integration": (["nature-integration"], []),
"needle-drop": (["sound-design"], []),
"negative-space": (["restraint"], []),
"negative-space framing": (["restraint"], []),
"no-compromise": (["precision"], []),
"nonlinear-structure": (["long-form-structure"], []),
"nostalgia": ([], ["nostalgia"]),
"nostalgia-as-texture": ([], ["nostalgia"]),
"nostalgia-as-texture framing": ([], ["nostalgia"]),
"obsession": ([], ["cost-of-greatness"]),
"odds-as-product": (["offer-design"], []),
"offer-design": (["offer-design"], []),
"olfactive-shock": (["subversion"], []),
"open-air-bathing": (["indoor-outdoor"], []),
"open-plan": (["spatial-direction"], []),
"open-sky": (["indoor-outdoor"], []),
"operatic-excess": (["maximalism"], []),
"opulence": (["maximalism"], []),
"organic-shape": (["materiality"], []),
"ornament": (["maximalism"], []),
"outsiders": ([], ["belonging-and-exclusion"]),
"overlay": (["immersive-atmosphere"], []),
"owned-distribution": (["ownership-as-strategy"], []),
"owner-operator": (["ownership-as-strategy"], []),
"ownership-as-strategy": (["ownership-as-strategy"], []),
"pacing": (["long-form-structure"], []),
"packaging": (["art-direction"], []),
"packaging-design": (["art-direction"], []),
"pared-palette": (["restraint"], []),
"participation": (["hospitality"], []),
"passive-cooling": (["nature-integration"], []),
"patina": (["texture"], []),
"perseverance-and-identity": ([], ["perseverance"]),
"persona-as-asset": (["positioning"], []),
"personal-canon": (["taste-authority"], []),
"pinnacle standard": (["precision"], []),
"place-as-concept": (["sense-of-place"], []),
"place-as-experience": (["sense-of-place"], []),
"place-rooted": (["sense-of-place"], []),
"plant-density": (["biophilic"], []),
"platform-ecosystem": (["institution-building"], []),
"playful-eclecticism": (["high-low"], []),
"polymath": (["reinvention"], []),
"populist-craft": (["accessible-luxury"], []),
"positioning": (["positioning"], []),
"possessed-not-performed identity": ([], ["cultural-identity"]),
"power-and-identity": ([], ["class-and-identity"]),
"precision": (["precision"], []),
"precision-as-freedom": (["precision"], []),
"precision-as-freedom framing": (["precision"], []),
"premium": (["investment-luxury"], []),
"presence": (["immersive-atmosphere"], []),
"prestige": (["investment-luxury"], []),
"prestige-niche": (["investment-luxury"], []),
"price-transparency": (["positioning"], []),
"pride-and-hubris": ([], ["ambition-and-hubris"]),
"principled-craft": (["craft"], []),
"produce-first": (["provenance"], []),
"producer-as-architect": (["craft"], []),
"product-innovation": (["offer-design"], []),
"product-pivot": (["positioning"], []),
"professional-grade": (["precision"], []),
"proof-as-argument": (["proof-as-argument"], []),
"proportion-play": (["art-direction"], []),
"proposition": (["positioning"], []),
"provenance": (["provenance"], []),
"public-sculpture": (["scale"], []),
"quality-over-brand": (["anti-logo"], []),
"quiet-luxury": (["quiet-luxury"], []),
"quiet-luxury direction": (["quiet-luxury"], []),
"quiet-warmth": (["warmth"], []),
"ranked-shortlist": (["curation-strategy"], []),
"rare-ingredient": (["investment-luxury"], []),
"raw-and-warm": (["texture", "warmth"], []),
"rawness": (["texture"], []),
"rebrand": (["positioning"], []),
"reclaiming-the-canon": (["subversion"], []),
"reference-as-brief": (["curation-strategy"], []),
"refined": (["restraint"], []),
"regional-vernacular": (["sense-of-place"], []),
"reinvention": (["reinvention"], []),
"repetition": (["art-direction"], []),
"repositioned": (["positioning"], []),
"resilience": ([], ["perseverance"]),
"restrained": (["restraint"], []),
"restraint": (["restraint"], []),
"restraint-in-cut": (["restraint"], []),
"restraint-of-means": (["restraint"], []),
"retail editorial": (["merchandising"], []),
"retail-theatre": (["merchandising"], []),
"revision-in-public": (["reinvention"], []),
"rhetoric": (["rhetoric"], []),
"rigour": (["precision"], []),
"ritual": (["ritual"], []),
"role-play": (["hospitality"], []),
"rustic-refinement": (["texture"], []),
"scale": (["scale"], []),
"scarcity": (["positioning"], []),
"sculptural-mass": (["scale"], []),
"sculptural-silhouette": (["materiality"], []),
"seasonality": (["provenance"], []),
"secondary storefront": (["merchandising"], []),
"selective alignment": (["curation-strategy"], []),
"self-authorship": (["self-authorship"], []),
"self-education": (["self-education"], []),
"self-production": (["ownership-as-strategy"], []),
"self-sufficiency": (["ownership-as-strategy"], []),
"sense-of-place": (["sense-of-place"], []),
"sentiment": ([], ["emotional-honesty"]),
"sentiment-led": (["narrative"], []),
"signature-product": (["positioning"], []),
"signature-scent": (["positioning"], []),
"single-origin": (["provenance"], []),
"slang-as-brand": (["voice-and-tone"], []),
"slow-burn": (["long-form-structure"], []),
"small-production": (["provenance"], []),
"small-space-ingenuity": (["spatial-direction"], []),
"smallness-done-well": (["spatial-direction"], []),
"sonic-signature": (["sound-design"], []),
"sound-design": (["sound-design"], []),
"sourcing": (["provenance"], []),
"spatial-arrangement": (["spatial-direction"], []),
"spatial-direction": (["spatial-direction"], []),
"spatial-memory": (["spatial-direction"], []),
"spectacle": (["maximalism"], []),
"sprezzatura": (["restraint"], []),
"statement": (["conviction"], []),
"statement-with-control direction": (["restraint", "conviction"], []),
"status-object": (["investment-luxury"], []),
"status-scent": (["investment-luxury"], []),
"story-circle": (["narrative"], []),
"storytelling": (["narrative"], []),
"strategy": (["positioning"], []),
"street-to-gallery": (["high-low"], []),
"street-to-gallery framing": (["high-low"], []),
"structural-honesty": (["structural-honesty"], []),
"structure-as-argument": (["long-form-structure"], []),
"style-as-resistance": (["subversion"], []),
"style-as-resistance framing": (["subversion"], []),
"stylist": (["art-direction"], []),
"sub-line curation": (["curation-strategy"], []),
"subversion": (["subversion"], []),
"subversive": (["subversion"], []),
"surreal-expressionism": (["art-direction"], []),
"suspense": (["long-form-structure"], []),
"sustainability": (["nature-integration"], []),
"systems-as-creativity": (["institution-building"], []),
"tactile": (["texture"], []),
"taste proxy": (["taste-authority"], []),
"taste-authority": (["taste-authority"], []),
"taste-compass framing": (["taste-authority"], []),
"taste-evolution framing": (["taste-authority"], []),
"taste-proxy": (["taste-authority"], []),
"technical-innovation": (["precision"], []),
"technical-precision": (["precision"], []),
"technique": (["craft"], []),
"terroir": (["provenance"], []),
"textile": (["materiality"], []),
"textile-and-symbol": (["materiality"], []),
"texture": (["texture"], []),
"texture-over-ornament": (["texture"], []),
"textured": (["texture"], []),
"the-canon": (["taste-authority"], []),
"the-uncanny": (["immersive-atmosphere"], []),
"theatre-and-secrecy": (["immersive-atmosphere"], []),
"theatrical": (["maximalism"], []),
"three-continent-fusion": (["cultural-bridge"], []),
"threshold": (["indoor-outdoor"], []),
"tiered curation": (["curation-strategy"], []),
"timeless-system": (["structural-honesty"], []),
"tonal-range": ([], ["emotional-honesty"]),
"total-commitment": ([], ["cost-of-greatness"]),
"total-design": (["art-direction"], []),
"transformation": ([], ["transformation"]),
"tribal identity": ([], ["cultural-identity"]),
"truth-over-accuracy": (["conviction"], []),
"two-ingredient": (["restraint"], []),
"typography": (["typography"], []),
"ultra-luxury": (["investment-luxury"], []),
"unambiguous loyalty": ([], ["cultural-identity"]),
"uncompromising-position": (["conviction"], []),
"upscale-social": (["hospitality"], []),
"urban-vernacular": (["sense-of-place"], []),
"utility": (["structural-honesty"], []),
"values-led": (["moral-clarity"], []),
"virtual-world": (["immersive-atmosphere"], []),
"visual-bravura": (["art-direction"], []),
"visual-direction": (["art-direction"], []),
"visual-system": (["art-direction"], []),
"voice-and-tone": (["voice-and-tone"], []),
"voice-as-instrument": (["sound-design"], []),
"vulnerability": ([], ["vulnerability"]),
"vulnerability-and-grandiosity": ([], ["vulnerability"]),
"walk-away-power": (["conviction"], []),
"warm": (["warmth"], []),
"warm-minimalism": (["warmth", "restraint"], []),
"warm-modernism": (["warmth"], []),
"warmth": (["warmth"], []),
"water-and-garden": (["biophilic"], []),
"wellbeing": (["wellbeing"], []),
"wellness": (["wellbeing"], []),
"wellness-design": (["wellbeing"], []),
"wit": (["subversion"], []),
"wonder": ([], ["dreams-and-ambition"]),
"world-building": (["world-building"], []),
}

ALL_PULL = [h for g in PULL_FOR.values() for h in g]

# Card-level overrides: cards whose Pull-for line was entirely subject descriptors,
# assigned by reading the card body.
OVERRIDES = {
    "lafayette-street": ["accessible-luxury", "sense-of-place"],
    "millesime-imperial": ["investment-luxury", "heritage"],
    "rebecca-maria": ["art-direction", "high-low"],
    "tyrod-taylor": ["restraint", "conviction"],
}
